- name: "MASTER, INFRA and NODE: Removing SSH"
  gce_tag: instance_name={{ item.hostname }} state=absent zone={{ gce_zone }}
           tags="enable-ssh"
           pem_file={{ gce_credentials_file }}
           project_id={{ gce_project_id }} service_account_email={{ gce_service_account_email }}
  with_items: "{{ master_definition }}+{{ infra_definition }}+{{ node_definition }}"
  tags: [ ocp, gce, tag, final_steps, ssh ]
