- name: "BASTION: Delete instance: {{ bastion_definition.hostname }}"
  azure_rm_virtualmachine: name={{ bastion_definition.hostname }} state=absent
                           resource_group={{ name }} location={{ region }}
                           subscription_id={{ azure_subscription_id }} tenant={{ azure_tenant }}
                           client_id={{ azure_client_id }} secret={{ azure_secret }}
  ignore_errors: True
  tags: [ ocp, azure, delete, bastion ]

- name: "BASTION: Delete Network Interface: {{ bastion_definition.hostname }}"
  azure_rm_networkinterface: name={{ bastion_definition.hostname }} state=absent
                             resource_group={{ name }} location={{ region }}
                             subscription_id={{ azure_subscription_id }} tenant={{ azure_tenant }}
                             client_id={{ azure_client_id }} secret={{ azure_secret }}
  ignore_errors: True
  tags: [ ocp, azure, delete, bastion ]

- name: "BASTION: Delete Public IP: {{ bastion_definition.hostname }}"
  azure_rm_publicipaddress: name={{ bastion_definition.hostname }} state=absent
                            resource_group={{ name }} location={{ region }}
                            subscription_id={{ azure_subscription_id }} tenant={{ azure_tenant }}
                            client_id={{ azure_client_id }} secret={{ azure_secret }}
  ignore_errors: True
  tags: [ ocp, azure, delete, bastion ]

- name: "MASTER, INFRA and NODE: Delete all instances"
  azure_rm_virtualmachine: name={{ item.hostname }} state=absent
                           resource_group={{ name }} location={{ region }}
                           subscription_id={{ azure_subscription_id }} tenant={{ azure_tenant }}
                           client_id={{ azure_client_id }} secret={{ azure_secret }}
  with_items: "{{ master_definition }}+{{ infra_definition }}+{{ node_definition }}"
  ignore_errors: True
  tags: [ ocp, azure, delete, master ]

- name: "MASTER, INFRA and NODE: Delete Network Interface"
  azure_rm_networkinterface: name={{ item.hostname }} state=absent
                             resource_group={{ name }} location={{ region }}
                             subscription_id={{ azure_subscription_id }} tenant={{ azure_tenant }}
                             client_id={{ azure_client_id }} secret={{ azure_secret }}
  with_items: "{{ master_definition }}+{{ infra_definition }}+{{ node_definition }}"
  ignore_errors: True
  tags: [ ocp, azure, delete, master ]

- name: "MASTER, INFRA and NODE: Delete all Public IP"
  azure_rm_publicipaddress: name={{ item.hostname }} state=absent
                            resource_group={{ name }} location={{ region }}
                            subscription_id={{ azure_subscription_id }} tenant={{ azure_tenant }}
                            client_id={{ azure_client_id }} secret={{ azure_secret }}
  with_items: "{{ master_definition }}+{{ infra_definition }}+{{ node_definition }}"
  ignore_errors: True
  tags: [ ocp, azure, delete, master ]
